import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["'Be Vietnam Pro'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "1.1" }],
        "headline-md": ["1.75rem", { lineHeight: "1.2" }],
        "title-lg": ["1.375rem", { lineHeight: "1.3" }],
        "body-lg": ["1rem", { lineHeight: "1.5" }],
        "label-md": ["0.75rem", { lineHeight: "1.5" }],
      },
      colors: {
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#00454c",
        "on-surface-variant": "#564334",
        "inverse-primary": "#ffb77d",
        "on-secondary-fixed-variant": "#544600",
        "surface": "#fff8f6",
        "surface-container-high": "#f3e5e2",
        "on-background": "#211a18",
        "on-tertiary-fixed": "#001f23",
        "secondary-container": "#fcd400",
        "surface-container-highest": "#eedfdc",
        "on-error-container": "#93000a",
        "surface-bright": "#fff8f6",
        "inverse-surface": "#372f2d",
        "secondary": "#705d00",
        "surface-container": "#f9ebe8",
        "tertiary-fixed-dim": "#96d0d8",
        "on-secondary-container": "#6e5c00",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb77d",
        "surface-container-low": "#fff0ed",
        "primary-container": "#FF8C00",
        "surface-dim": "#e5d7d4",
        "primary-fixed": "#ffdcc3",
        "outline-variant": "#ddc1ae",
        "on-primary-fixed-variant": "#6e3900",
        "secondary-fixed-dim": "#e9c400",
        "primary": "#FF8C00",
        "secondary-fixed": "#ffe16d",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#fff8f6",
        "on-secondary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#074f56",
        "surface-variant": "#eedfdc",
        "on-primary-fixed": "#2f1500",
        "on-primary-container": "#623200",
        "surface-tint": "#FF8C00",
        "inverse-on-surface": "#fceeea",
        "tertiary-container": "#79b3bb",
        "outline": "#897362",
        "on-error": "#ffffff",
        "tertiary": "#2a676e",
        "error": "#ba1a1a",
        "on-surface": "#211a18",
        "tertiary-fixed": "#b1edf5",
        "error-container": "#ffdad6"
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(55, 47, 45, 0.06)",
      },
      borderRadius: {
        lg: "2rem",
        xl: "3rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
